name: Node.js Package
on: 
  push:
    branches:
      - main
      - dev
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'
          registry-url: https://npm.pkg.github.com/
      - run: bun install --registry=https://registry.npmjs.org/
      - name: Publish with version based on branch
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            bun publish --tag="latest"
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            bun publish --tag="next"
          fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
