name: Node.js Package
on: 
  push:
    branches:
      - main
      - dev
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - name: Set version based on branch
        id: versioning
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "version=$(npm version patch --no-git-tag-version)" >> $GITHUB_ENV
          elif [ "${{ github.ref_name }}" == "dev" ]; then
            echo "version=$(npm version prerelease --preid=beta --no-git-tag-version)" >> $GITHUB_ENV
          fi
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
